### ISSUE TITLE
Issues with Github Enterprise

### ISSUE THREAD

**Issue by lhasadad** [liberapay/git-lfs-fetch.py#4]
I was trying to work with the module against a GHE based repository and found some authentication issues.  I think I have them resolved in a copy I have if you don't mind I will fork and provide a pull request to donate back the changes.

**Comment by Changaco** [comment]
@lhasadad Go ahead, I'll merge your changes if they look fine to me.

**Comment by lhasadad** [comment]
Pull request is in.

**Comment by lhasadad** [comment]
branch has been pulled into master repository,  closing issue.
