### ISSUE TITLE
Issue downloading LFS file from github

### ISSUE THREAD

**Issue by aalugore** [liberapay/git-lfs-fetch.py#8]
Hello! I am having an issue where I do not have access to git-lfs proper, but do have access to this. Can I get a usage example on how to use this tool? specifically, I want to download the lfs file referenced in this file:
https://github.com/NVIDIA/DALI_extra/blob/master/db/MNIST/testing/data.mdb

Is that possible with this tool?

**Comment by Changaco** [comment]
The tool isn't designed to download a particular file, it downloads all the externally stored files referenced in the repository.

**Comment by aalugore** [comment]
That would work as well. What would be the usage example if I wanted all externally stored lfs files in the DALI_extra repo?

**Comment by Changaco** [comment]
Just run `python -m git_lfs` in the repository where you've cloned the DALI_extra repository.
